models/notes/views.py
from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect
from src.models.notes.note import Note
import src.models.users.decorators as user_decorators
from src.models.users.user import User
from src.models.error_logs.error_log import Error_
import traceback

note_blueprint = Blueprint('notes', __name__)


@note_blueprint.route('/my_notes/')
@user_decorators.require_login
def user_notes():
    try:
        user = User.find_by_email(session['email'])
        user_notes = User.get_notes(user)
        user_name = user.email

        return render_template('/notes/my_notes.html', user_name=user_name, user_notes=user_notes)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='user note reading USER:' + session['email'])
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during reading your notes...')


@note_blueprint.route('/note/<string:note_id>')
def note(note_id):

    try:
        note = Note.find_by_id(note_id)
        user = User.find_by_email(note.author_email)

        try:
            if note.author_email == session['email']:
                author_email_is_session = True
            else:
                author_email_is_session = False

        except:
            author_email_is_session = False

        finally:

            return render_template('/notes/note.html', note=note,
                                   author_email_is_session=author_email_is_session, msg_=False, user=user)

    except:
        error_msg = traceback.format_exc().split('\n')

        try:

            Error_obj = Error_(error_msg=''.join(error_msg), error_location='note reading NOTE:' + note._id)
        except:
            Error_obj = Error_(error_msg=''.join(error_msg), error_location='note reading NOTE:NONE')

        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during reading your note...')


@note_blueprint.route('/add_note', methods=['GET', 'POST'])
@user_decorators.require_login
def create_note():

    try:
        if request.method == 'POST':
            share = request.form['inputGroupSelect01']

            if share == '0':
                return render_template('/notes/create_note.html',
                                       error_msg="You did not selected an Share label. Please select an Share label.")

            if share == '1':
                share = True
                share_only_with_users = False

            else:
                share = False
                share_only_with_users = True

            title = request.form['title']
            content = request.form['content']
            author_email = session['email']
            author_nickname = User.find_by_email(author_email).nick_name

            note_for_save = Note(title=title, content=content, author_email=author_email, shared=share,
                                 author_nickname=author_nickname ,share_only_with_users=share_only_with_users)
            note_for_save.save_to_mongo()

            return redirect(url_for('.user_notes'))

        return render_template('/notes/create_note.html')

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='create_note creating note')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during saving your note...')


@note_blueprint.route('/delete_note/<string:note_id>')
@user_decorators.require_login
def delete_note(note_id):

    try:
        Note.find_by_id(note_id).delete()
    finally:
        return redirect(url_for('.user_notes'))


@note_blueprint.route('/share_note/<string:note_id>')
@user_decorators.require_login
def share_note(note_id):

    try:
        Note.find_by_id(note_id).share_or_unshare()
    finally:
        return redirect(url_for('.note', note_id=note_id, msg='Your note is shared!!', msg_=True))


@note_blueprint.route('/pub_notes/')
def notes():

    try:

        try:
            if session['email'] is None:
                return render_template('/notes/pub_notes.html', notes=Note.find_shared_notes())
            else:
                return render_template('/notes/pub_notes.html',
                                       notes=Note.get_only_with_users() + Note.find_shared_notes())
        except:
            return render_template('/notes/pub_notes.html', notes=Note.find_shared_notes())

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='notes publick note reading')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during reading users notes...')


@note_blueprint.route('/edit_note/<string:note_id>', methods=['GET', 'POST'])
@user_decorators.require_login
def edit_note(note_id):

    try:
        note = Note.find_by_id(note_id)

        if request.method == 'POST':

            if request.method == 'POST':
                share = request.form['inputGroupSelect01']

                if share == '0':
                    return render_template('/notes/create_note.html',
                                           error_msg="You did not selected an Share label. Please select an Share label.")

                if share == '1':
                    share = True
                    share_only_with_users = False

                else:
                    share = False
                    share_only_with_users = True

            title = request.form['title']
            content = request.form['content']

            note.shared = share
            note.share_only_with_users = share_only_with_users
            note.title = title
            note.content = content
            note.save_to_mongo()

            return redirect(url_for('.note', note_id=note_id))

        else:
            return render_template('/notes/edit_note.html', note=note)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='edit_note saveing and getting input from html file')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during saving your note...')

models/users/views.py
import datetime
import time
import traceback

from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect
import src.models.users.errors as UserErrors
from src.common.utils import Utils
from src.models.error_logs.error_log import Error_
from src.models.messages.message import Message
from src.models.notes.note import Note
from src.models.users.user import User
import src.models.users.decorators as user_decorators

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():

    try:
        e = ''
        if request.method == 'POST':

            email = request.form['email']
            password = request.form['password']

            try:
                if User.is_login_valid(email, password):
                    session['email'] = email
                    user = User.find_by_email(email)
                    session['_id'] = user._id
                    user.last_logined = datetime.datetime.now()
                    user.save_to_mongo()
                    return redirect(url_for("home"))

            except UserErrors.UserError as e:
                return render_template("users/login.html", message=e)

        return render_template("users/login.html", message=e)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='login_user while logining user')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during login...')


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():

    try:
        if request.method == 'POST':

            email = request.form['email']
            password = request.form['password']
            nick_name = request.form['nickname']

            try:
                if User.register_user(email, password, nick_name):
                    session['email'] = email
                    message = Message(title="Welcome to Note-it™!",
                                      content="""Welcome to Note-it! You can make a note,
                                            and share it with other users! Or you can
                                            just keep the note to your selves.
                                            You can send messages to other users too! Check out this website!!""",
                                      reciver_id=User.find_by_email(email)._id,
                                      sender_id=User.find_by_email('SE@SENOREPLAY.COM')._id)
                    message.save_to_db()
                    return redirect(url_for("home"))

            except UserErrors.UserError as e:
                return e.message

        return render_template("users/register.html")

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='register_user while registering user')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during registering you...')


#@user_blueprint.route('/alerts')
#@user_decorators.require_login
#def user_notes():
#    user = User.find_by_email(session['email'])
#    alerts = user.get_alerts()
#    user_name = user.email
#    return render_template('users/alerts.html', alerts=alerts, user_name=user_name)


@user_blueprint.route('/logout')
@user_decorators.require_login
def logout_user():
    session['email'] = None
    session['_id'] = None

    return redirect(url_for('home'))


@user_blueprint.route('/users', methods=['GET', 'POST'])
def users_page():
    try:
        users = User.get_all()
        # TODO: 일래스틱서치 배우고 완료하기
        return render_template('/users/users_page.html', users=users)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='users_page while loading users info and posting to html')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during reading information...')


@user_blueprint.route('/user/<string:user_id>')
def user_page(user_id):

    try:
        try:
            user = User.find_by_id(user_id)
        except:
            user = User.find_by_email(user_id)
        user_notes = Note.find_shared_notes_by_user(user.email)

        return render_template('/users/user.html', user=user, user_notes=user_notes, user_note_count=len(user_notes))

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg),
                           error_location='user_page while loading user{} info'.format(user_id))
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during reading information...')


@user_blueprint.route('/delete_user/<string:user_id>', methods=['GET', 'POST'])
@user_decorators.require_login
def delete_user(user_id):

    try:
        if request.method == 'POST':
            user = User.find_by_id(user_id)
            user.delete_user_notes()
            user.delete()
            session['email'] = None
            return redirect(url_for('home'))

        return render_template('/users/confrim.html')

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='delete_user while removing user from database')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during deleting your account...')


@user_blueprint.route('/edit_user/<string:user_id>', methods=['GET', 'POST'])
@user_decorators.require_login
def edit_user(user_id):

    try:
        current_user = User.find_by_id(user_id)

        if request.method == 'POST':

            nick_name = request.form['nickname']

            current_user.nick_name = nick_name
            current_user.save_to_mongo()

            return redirect(url_for('.user_page', user_id=user_id))

        return render_template("users/edit_user.html", user=current_user)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg),
                           error_location='edit_user while finding user/saving changes to database')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during saving changes...')

templates/notes/create_note.html
{% extends "base.html" %}
{% block title %}
    <title>Note-it™ | Create Note</title>
{% endblock %}
{% block content %}

    {% if error_msg %}
        <div class="alert alert-danger" role="alert">
            <i class="fas fa-exclamation-triangle"></i> {{ error_msg }}
        </div>
    {% endif %}

    <div class="jumbotron form-sizer">

        <h1><i class="fas fa-plus-square"></i> Create a Note</h1>

        <p>Fill in the blanks, and submit!</p>

    </div>

    <br>

    <div class="form-size jumbotron">
        <form method="post">

            <div class="form-group">

                <label for="title">Title</label>
                <input type="text" class="form-control" name="title" id="title" placeholder="Example title" aria-describedby="titleBlock">

                <small id="titleBlock" class="form-text text-muted">Here, you can put your note's title.</small>

            </div>

            <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <label class="input-group-text" for="inputGroupSelect01">Share label</label>
                      </div>
                      <select class="custom-select" id="inputGroupSelect01" name="inputGroupSelect01" required>

                        <option selected value="0">Choose...</option>
                        <option value="1">Share with all </option>
                        <option value="2">Share with only Note-it™ users</option>

                      </select>
            </div>



            <div class="input-group mb-3">

                <div class="input-group-prepend">
                        <label class="input-group-text" for="inputGroupSelect01">Content</label>
                </div>
                <textarea class="form-control text_box_big" name="content" id="content" placeholder="Example content" aria-describedby="contentBlock"></textarea>
            </div>

            <br>
            <button type="submit" class="btn btn-primary" style="">Save Note</button>

        </form>
    </div>

{% endblock %}

templates/notes/edit_note.html
{% extends "base.html" %}
{% block title %}
    <title>Note-it™ | Edit note</title>
{% endblock %}
{% block content %}

    <div class="jumbotron form-sizer">

        <h1><i class="far fa-edit"></i> Edit Note: {{ note.title }}</h1>

        <p>Fill in the blanks, and submit!</p>

    </div>

    <br>

    <div class="form-size jumbotron">
        <form method="post">

            <div class="form-group">

                <label for="title">Title</label>
                <input type="text" class="form-control" name="title" id="title" placeholder="Example title" aria-describedby="titleBlock" value="{{ note.title }}">

                <small id="titleBlock" class="form-text text-muted">Here, you can put your note's title.</small>

            </div>

            <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <label class="input-group-text" for="inputGroupSelect01">Share label</label>
                      </div>
                      <select class="custom-select" id="inputGroupSelect01" name="inputGroupSelect01" required>

                          <option value="0">Choose...</option>
                          {% if note.shared == True %}

                              <option value="1" selected>Share with all </option>
                                <option value="2">Share with only Note-it™ users</option>
                          {% else %}
                                <option value="1">Share with all </option>
                              <option value="2" selected>Share with only Note-it™ users</option>

                          {% endif %}

                      </select>
            </div>

            <div class="input-group">

                <div class="input-group-prepend">
                    <label for="content" class="input-group-text">Content</label>
                </div>

            <textarea class="form-control text_box_big" name="content" id="content" placeholder="Example content" aria-describedby="contentBlock">
                {{ note.content.strip() }}
            </textarea>


            </div>

            <br>
            <button type="submit" class="btn btn-primary">Save Note</button>

        </form>
    </div>

{% endblock %}

templates/notes/my_notes.html
{% extends "base.html" %}
{% block title %}
    <title>Note-it™ | My Notes</title>
{% endblock %}
{% block content %}

    <div class="page-header">

        <h1><strong>{{ user_name.split('@')[0] }}</strong>'s Notes</h1>

    </div>

    <hr class="my-4">

    <div class="list-group">

        {% if user_notes == [] or user_notes == None %}

            <div class="alert alert-primary" role="alert"><i class="fas fa-info-circle"></i>
                There are no notes!You can make a note by clicking the button below.
            </div>

        {% endif %}

        {% for note in user_notes %}

             <a href="{{ url_for('notes.note', note_id=note._id) }}" class="list-group-item list-group-item-action flex-column align-items-start">

                 <div class="d-flex w-100 justify-content-between">
                        <h4 class="mb-1">
                    {{ note.title }}</h4>

                     <p class="list-group-item-text">Created date <strong>{{ note.created_date.strftime("%Y-%m-%d at %H:%M") }}</strong></p>
                 </div>

            </a>

        {% endfor %}
    </div>

    <br>

    <a href="{{ url_for('notes.create_note') }}" class="btn btn-outline-success" role="button">Make a new note</a>

{% endblock %}

templates/notes/note.html
{% extends "base.html" %}

{% block title %}
    <title>Note-it™ | Note {{ note.title }}</title>
{% endblock %}

{% block content %}

    <div class="card">

        <div class="card-body">
            <h1><small>Note     </small><strong>  {{ note.title }}</strong> </h1>  <p class="text-muted">Author: {{ note.author_nickname }}</p>
            <p class="text-muted">{{ note.created_date.strftime("%Y-%m-%d at %H:%M") }}</p>
        </div>

    </div>

    <hr class="my-4">

    <div class="jumbotron">

        <div class="container">
            <p class="text-center font-weight-bold"><bold>{{ note.content }}</bold></p>
        </div>

    </div>

    <hr class="my-4">

    <div class="card">

        <div class="card-body">

            <a href="{{ url_for('users.user_page', user_id=user._id) }}" class="btn btn-outline-secondary" role="button">View Author ({{ note.author_nickname }})</a>

            <a href="{{ url_for('message.send_note_radio', note_id=note._id) }}" class="btn btn-outline-info" role="button">Send Note</a>

            {% if author_email_is_session %}

                <a href="{{ url_for('.delete_note', note_id=note._id) }}" class="btn btn-outline-danger" role="button">Delete</a>

                <a href="{{ url_for('.edit_note', note_id=note._id) }}" class="btn btn-outline-info" role="button">Edit</a>

            {% endif %}

        </div>

    </div>

{% endblock %}

templates/notes/pub_notes.html
{% extends "base.html" %}
{% block title %}
    <title>Note-it™ | Public Notes</title>
{% endblock %}

{% block content %}

    <div class="content">

        <h1><i class="far fa-clone"></i> Public Notes <small class="text-muted">shared notes</small></h1>

    </div>

<hr class="my-4">

    <div class="list-group">

        {% if notes == [] or notes == None %}

            <div class="alert alert-primary" role="alert">
                <i class="far fa-frown"></i> There are no shared notes.
            </div>

        {% endif %}

        {% for note in notes %}

            <a href="{{ url_for('notes.note', note_id=note._id) }}" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                    <h2 class="mb-1"><i class="fas fa-sticky-note"></i> {{ note.title }}</h2>
                    <p class="list-group-item-text">Author: {{ note.author_nickname }}</p>
                </div>

                <div class="d-flex w-100 justify-content-between">
                    <p class="mb-1"></p>
                    <p class="list-group-item-text">Created date: {{ note.created_date.strftime("%Y-%m-%d at %H:%M") }}</p>
                </div>

            </a>

        {% endfor %}

    </div>

{% endblock %}