models/notes/views.py
from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect
from src.models.notes.note import Note
import src.models.users.decorators as user_decorators
from src.models.users.user import User
from src.models.error_logs.error_log import Error_
import traceback

note_blueprint = Blueprint('notes', __name__)


@note_blueprint.route('/my_notes/')
@user_decorators.require_login
def user_notes():
    try:
        user = User.find_by_email(session['email'])
        user_notes = User.get_notes(user)
        user_name = user.email

        return render_template('/notes/my_notes.html', user_name=user_name, user_notes=user_notes)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='user note reading USER:' + session['email'])
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during reading your notes...')


@note_blueprint.route('/note/<string:note_id>')
def note(note_id):

    try:
        note = Note.find_by_id(note_id)
        user = User.find_by_email(note.author_email)

        try:
            if note.author_email == session['email']:
                author_email_is_session = True
            else:
                author_email_is_session = False

        except:
            author_email_is_session = False

        finally:

            return render_template('/notes/note.html', note=note,
                                   author_email_is_session=author_email_is_session, msg_=False, user=user)

    except:
        error_msg = traceback.format_exc().split('\n')

        try:

            Error_obj = Error_(error_msg=''.join(error_msg), error_location='note reading NOTE:' + note._id)
        except:
            Error_obj = Error_(error_msg=''.join(error_msg), error_location='note reading NOTE:NONE')

        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during reading your note...')


@note_blueprint.route('/add_note', methods=['GET', 'POST'])
@user_decorators.require_login
def create_note():

    try:
        if request.method == 'POST':
            share = request.form['inputGroupSelect01']

            if share == '0':
                return render_template('/notes/create_note.html',
                                       error_msg="You did not selected an Share label. Please select an Share label.")

            if share == '1':
                share = True
                share_only_with_users = False

            else:
                share = False
                share_only_with_users = True

            title = request.form['title']
            content = request.form['content']
            author_email = session['email']
            author_nickname = User.find_by_email(author_email).nick_name

            note_for_save = Note(title=title, content=content, author_email=author_email, shared=share,
                                 author_nickname=author_nickname ,share_only_with_users=share_only_with_users)
            note_for_save.save_to_mongo()

            return redirect(url_for('.user_notes'))

        return render_template('/notes/create_note.html')

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='create_note creating note')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during saving your note...')


@note_blueprint.route('/delete_note/<string:note_id>')
@user_decorators.require_login
def delete_note(note_id):

    try:
        Note.find_by_id(note_id).delete()
    finally:
        return redirect(url_for('.user_notes'))


@note_blueprint.route('/share_note/<string:note_id>')
@user_decorators.require_login
def share_note(note_id):

    try:
        Note.find_by_id(note_id).share_or_unshare()
    finally:
        return redirect(url_for('.note', note_id=note_id, msg='Your note is shared!!', msg_=True))


@note_blueprint.route('/pub_notes/')
def notes():

    try:

        try:
            if session['email'] is None:
                return render_template('/notes/pub_notes.html', notes=Note.find_shared_notes())
            else:
                return render_template('/notes/pub_notes.html',
                                       notes=Note.get_only_with_users() + Note.find_shared_notes())
        except:
            return render_template('/notes/pub_notes.html', notes=Note.find_shared_notes())

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='notes publick note reading')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during reading users notes...')


@note_blueprint.route('/edit_note/<string:note_id>', methods=['GET', 'POST'])
@user_decorators.require_login
def edit_note(note_id):

    try:
        note = Note.find_by_id(note_id)

        if request.method == 'POST':

            if request.method == 'POST':
                share = request.form['inputGroupSelect01']

                if share == '0':
                    return render_template('/notes/create_note.html',
                                           error_msg="You did not selected an Share label. Please select an Share label.")

                if share == '1':
                    share = True
                    share_only_with_users = False

                else:
                    share = False
                    share_only_with_users = True

            title = request.form['title']
            content = request.form['content']

            note.shared = share
            note.share_only_with_users = share_only_with_users
            note.title = title
            note.content = content
            note.save_to_mongo()

            return redirect(url_for('.note', note_id=note_id))

        else:
            return render_template('/notes/edit_note.html', note=note)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='edit_note saveing and getting input from html file')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during saving your note...')

models/users/views.py
import datetime
import time
import traceback

from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect
import src.models.users.errors as UserErrors
from src.common.utils import Utils
from src.models.error_logs.error_log import Error_
from src.models.messages.message import Message
from src.models.notes.note import Note
from src.models.users.user import User
import src.models.users.decorators as user_decorators

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():

    try:
        e = ''
        if request.method == 'POST':

            email = request.form['email']
            password = request.form['password']

            try:
                if User.is_login_valid(email, password):
                    session['email'] = email
                    user = User.find_by_email(email)
                    session['_id'] = user._id
                    user.last_logined = datetime.datetime.now()
                    user.save_to_mongo()
                    return redirect(url_for("home"))

            except UserErrors.UserError as e:
                return render_template("users/login.html", message=e)

        return render_template("users/login.html", message=e)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='login_user while logining user')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during login...')


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():

    try:
        if request.method == 'POST':

            email = request.form['email']
            password = request.form['password']
            nick_name = request.form['nickname']

            try:
                if User.register_user(email, password, nick_name):
                    session['email'] = email
                    message = Message(title="Welcome to Note-it™!",
                                      content="""Welcome to Note-it! You can make a note,
                                            and share it with other users! Or you can
                                            just keep the note to your selves.
                                            You can send messages to other users too! Check out this website!!""",
                                      reciver_id=User.find_by_email(email)._id,
                                      sender_id=User.find_by_email('SE@SENOREPLAY.COM')._id)
                    message.save_to_db()
                    return redirect(url_for("home"))

            except UserErrors.UserError as e:
                return e.message

        return render_template("users/register.html")

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='register_user while registering user')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during registering you...')


#@user_blueprint.route('/alerts')
#@user_decorators.require_login
#def user_notes():
#    user = User.find_by_email(session['email'])
#    alerts = user.get_alerts()
#    user_name = user.email
#    return render_template('users/alerts.html', alerts=alerts, user_name=user_name)


@user_blueprint.route('/logout')
@user_decorators.require_login
def logout_user():
    session['email'] = None
    session['_id'] = None

    return redirect(url_for('home'))


@user_blueprint.route('/users', methods=['GET', 'POST'])
def users_page():
    try:
        users = User.get_all()
        # TODO: 일래스틱서치 배우고 완료하기
        return render_template('/users/users_page.html', users=users)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='users_page while loading users info and posting to html')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during reading information...')


@user_blueprint.route('/user/<string:user_id>')
def user_page(user_id):

    try:
        try:
            user = User.find_by_id(user_id)
        except:
            user = User.find_by_email(user_id)
        user_notes = Note.find_shared_notes_by_user(user.email)

        return render_template('/users/user.html', user=user, user_notes=user_notes, user_note_count=len(user_notes))

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg),
                           error_location='user_page while loading user{} info'.format(user_id))
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during reading information...')


@user_blueprint.route('/delete_user/<string:user_id>', methods=['GET', 'POST'])
@user_decorators.require_login
def delete_user(user_id):

    try:
        if request.method == 'POST':
            user = User.find_by_id(user_id)
            user.delete_user_notes()
            user.delete()
            session['email'] = None
            return redirect(url_for('home'))

        return render_template('/users/confrim.html')

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='delete_user while removing user from database')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during deleting your account...')


@user_blueprint.route('/edit_user/<string:user_id>', methods=['GET', 'POST'])
@user_decorators.require_login
def edit_user(user_id):

    try:
        current_user = User.find_by_id(user_id)

        if request.method == 'POST':

            nick_name = request.form['nickname']

            current_user.nick_name = nick_name
            current_user.save_to_mongo()

            return redirect(url_for('.user_page', user_id=user_id))

        return render_template("users/edit_user.html", user=current_user)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg),
                           error_location='edit_user while finding user/saving changes to database')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during saving changes...')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    {% block title %}

    {% endblock %}

    {% include 'html_dependencies.html' %}

</head>
<body>

<br><br><br>

    <nav class="navbar navbar-expand-lg navbar-light bg-light  fixed-top" style="background-color: #e3f2fd;">

        <div class="container">

            <div class="navbar-header">

                <a href="/" class="navbar-brand" title="Home"><i class="far fa-sticky-note"></i>   Note-it™</a>
            </div>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navbarSupportedContent" class="collapse navbar-collapse">

                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active"><a href="{{ url_for('notes.notes') }}" class="nav-link"><i class="far fa-clone"></i> Shared Notes</a></li>
                    <li class="nav-item active"><a href="{{ url_for('users.users_page') }}" class="nav-link"><i class="fas fa-users"></i> Users</a></li>
                </ul>

                {% if session['email'] %}

                    <ul class="nav navbar-nav navbar-right justify-content-end ml-auto">
                        <li class="nav-item active"><a href="{{ url_for('notes.user_notes') }}" class="nav-link"><i class="fas fa-sticky-note"></i>    My Notes</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right justify-content-end">
                        <li class="nav-item active"><a href="{{ url_for('users.user_page', user_id=session['email']) }}" class="nav-link"><i class="fas fa-user-circle"></i>    My Profile</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right justify-content-end ">
                        <li class="nav-item active"><a href="{{ url_for('home2') }}" class="nav-link"><i class="fas fa-envelope"></i>  Message Center™</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right justify-content-end ">
                        <li class="nav-item active"><a href="{{ url_for('users.logout_user') }}" class="nav-link"><i class="fas fa-sign-out-alt"></i>    Log out</a></li>
                    </ul>

                {% else %}

                    <ul class="nav navbar-nav navbar-right justify-content-end ml-auto">
                        <li class="nav-item active"><a href="{{ url_for('users.register_user') }}" class="nav-link"><i class="fas fa-user-plus"></i>   Sign up</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right justify-content-end">
                        <li class="nav-item active"><a href="{{ url_for('users.login_user') }}" class="nav-link"><i class="fas fa-sign-in-alt"></i> Log in</a></li>
                    </ul>

                {% endif %}

            </div>

        </div>

    </nav>

    <br>

    <div class="content container">
        {% block content %}

        {% endblock %}
    </div>

    <br><br><br><br><br><br><br><br><br><br><br><br><br><br>

    <footer>

        <div class="footer-size jumbotron">

            <h7><span class="glyphicon glyphicon-console"></span> Made by <a href="https://www.jetbrains.com/pycharm/">Pycharm</a>
                and
                <a href="http://flask.pocoo.org/">Flask</a> and <i class="fab fa-python"></i> <a href="https://www.python.org/">Python</a></h7>

            <hr class="my-4">

            <div class="alert alert-warning" role="alert">
                 <h5><i class="fas fa-exclamation-triangle"></i> WARNING: This page is still in test state. The full
                            version would be out soon!!
                 </h5>
            </div>

        </div>

    </footer>

</body>
</html>

templates/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}

    {% endblock %}

    {% include 'html_dependencies.html' %}
</head>
<body>
    <br><br><br>
    <nav class="navbar navbar-expand-lg navbar-light bg-light  fixed-top">

        <div class="container">

            <div class="navbar-header">

                <a href="/" class="navbar-brand" title="Home">Note-it™|</a><a href="{{ url_for('home2') }}" class="navbar-brand"><i class="fas fa-envelope-square"></i> Message Center™</a>
            </div>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navbarSupportedContent" class="collapse navbar-collapse">

                {% if session['email'] %}

                    <ul class="nav navbar-nav navbar-right justify-content-end ml-auto">
                        <li class="nav-item active"><a href="{{ url_for('message.my_recived_messages', user_id=session['_id']) }}" class="nav-link"><i class="fas fa-envelope"></i> Received Messages</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right justify-content-end ">
                        <li class="nav-item active"><a href="{{ url_for('message.my_sended_messages', user_id=session['_id']) }}" class="nav-link"><i class="fas fa-envelope"></i> Sended Messages</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right justify-content-end ">
                        <li class="nav-item active"><a href="{{ url_for('message.send_message') }}" class="nav-link"><i class="fas fa-external-link-square-alt"></i> Send Message</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right justify-content-end ">
                        <li class="nav-item active"><a href="{{ url_for('users.logout_user') }}" class="nav-link"><i class="fas fa-sign-out-alt"></i>    Log out</a></li>
                    </ul>

                {% else %}

                    <ul class="nav navbar-nav navbar-right justify-content-end ml-auto">
                        <li class="nav-item active"><a href="{{ url_for('users.register_user') }}" class="nav-link"><i class="fas fa-user-plus"></i>   Sign up</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right justify-content-end">
                        <li class="nav-item active"><a href="{{ url_for('users.login_user') }}" class="nav-link"><i class="fas fa-sign-in-alt"></i> Log in</a></li>
                    </ul>

                {% endif %}


            </div>

        </div>

    </nav>

    {% block navbar %}

    {% endblock %}

    <br>

    <div class="content container">
        {% block content %}

        {% endblock %}
    </div>

    <br><br><br><br><br><br><br><br><br><br><br><br><br><br>

    <footer>

        <div class="footer-size jumbotron">

            <h7><span class="glyphicon glyphicon-console"></span> Made by <a href="https://www.jetbrains.com/pycharm/">Pycharm</a>
                and
                <a href="http://flask.pocoo.org/">Flask</a> and <i class="fab fa-python"></i> <a href="https://www.python.org/">Python</a></h7>

            <hr class="my-4">

            <div class="alert alert-warning" role="alert">
                 <h5><i class="fas fa-exclamation-triangle"></i> WARNING: This page is still in test state. The full
                            version would be out soon!!
                 </h5>
            </div>

        </div>

    </footer>
</body>
</html>

templates/error_page.html
{% extends "base.html" %}

{% block content %}

    <div class="card text-white bg-danger mb-3" style="">
  <div class="card-header">Error In Server</div>
  <div class="card-body">
    <h5 class="card-title"><i class="fas fa-exclamation-triangle"></i>  {{ error_msgr }}</h5>
    <p class="card-text">There was an error and the server crashed... Please report to the service center(010-2901-5627) or try again .
        We'll find an solution to this problem soon!  <i class="fas fa-smile"></i>
    </p>
  </div>
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block title %}
    <title>Note-it™ | A Online Note service</title>
{% endblock %}
{% block content %}

<div class="jumbotron">

    <h1><i class="far fa-sticky-note"></i> Note-it™. The world's notes!</h1>
    <p>Sign up, and use our note and alarm service!!</p>
    <p><a class="btn btn-outline-primary" href="{{ url_for('users.register_user') }}" role="button">Sign Up NOW!!</a></p>

</div>




{% endblock %}

templates/home2.html
{% extends "base2.html" %}
{% block title %}
    <title>Note-it™ | Message Center</title>
{% endblock %}

{% block content %}

    <div class="container jumbotron">

        <h1><i class="fas fa-envelope-square"></i> Welcome to Message Center!!</h1>

        <p>Here, you can send messages to other users with your Note-it™ account!!</p>

    </div>

    </div>

{% endblock %}

templates/html_dependencies.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">

<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

templates/loading.html
{% extends "base.html" %}

{% block title %}
    <title>Note-it™ | Loading...</title>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="fa-3x">
            <i class="fas fa-cog fa-spin"></i>
        </div>
    </div>

{% endblock %}