models/messages/views.py
import datetime
from src.models.error_logs.error_log import Error_
from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect
from src.models.messages.message import Message
import src.models.users.decorators as user_decorators
from src.models.notes.note import Note
from src.models.users.user import User
import traceback

message_blueprint = Blueprint('message', __name__)


@message_blueprint.route('/recived_messages/<string:user_id>')
@user_decorators.require_login
def my_recived_messages(user_id):
    try:
        messages = Message.find_by_reciver_id(user_id)
        user_nickname = User.find_by_id(session['_id']).nick_name

        return render_template('messages/my_recived_messages.html', messages=messages, user_nickname=user_nickname)
    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='my_recived_messages-during message finding')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during reading your messages')


@message_blueprint.route('/sended_messages/<string:user_id>')
@user_decorators.require_login
def my_sended_messages(user_id):
    try:
        messages = Message.find_by_sender_id(user_id)
        user_nickname = User.find_by_id(session['_id']).nick_name

        return render_template('messages/my_sended_messages.html', messages=messages, user_nickname=user_nickname)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='my_sended_messages-during message finding')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during reading your messages')


@message_blueprint.route('/send_message', methods=['GET', 'POST'])
@user_decorators.require_login
def send_message():

    try:
        all_users = User.get_all()
        recivers = []

        if request.method == 'POST':
            title = request.form['title']
            content = request.form['content']

            if request.form['reciver_email'] in [None, [], ""]:
                return render_template('messages/send_message.html',
                                       e='Your receiver field is empty. Please fill in at least ONE receiver.',
                                       all_users=all_users, title=title,
                                       content=content)

            try:
                # reciver_id = User.find_by_email(request.form['reciver_email'])._id
                recivers_string = request.form['reciver_email'].split()

                for email in recivers_string:
                    recivers.append(User.find_by_email(email)._id)

            except Exception:
                return render_template('messages/send_message.html', e="Please Check That you have coped EXACTLY the target user's email! And separated the emails with spaces!!"
                                       , all_users=all_users, title=title, content=content)

            sender_id = User.find_by_email(session['email'])._id

            message = Message(title=title, content=content, reciver_id=recivers, sender_id=sender_id, is_a_noteOBJ=False)
            message.save_to_mongo()

            return redirect(url_for('.my_sended_messages', user_id=sender_id))

        return render_template('messages/send_message.html', all_users=all_users)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='send_message message sending')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during sending your message...')


@message_blueprint.route('/message/<string:message_id>')
@user_decorators.require_login
def message(message_id, is_sended=False):

    try:

        message = Message.find_by_id(message_id)

        if message is None:
            return 'There was an server error. Please try again a another time!'

        if message.readed_by_reciver is False and is_sended is False and session['_id'] in message.reciver_id and message.readed_date is None:
            message.readed_by_reciver = True
            message.readed_date = datetime.datetime.now()
            message.save_to_mongo()

        sender_nickname = User.find_by_id(message.sender_id).nick_name
        if type(message.reciver_id) is list:
            reciver_nickname = []
            for reciver in message.reciver_id:
                reciver_nickname.append(User.find_by_id(reciver).nick_name)

        else:
            reciver_nickname = User.find_by_id(message.reciver_id).nick_name

        if message.is_a_noteOBJ:
            note = Note.find_by_id(message.content)
        else:
            note = None

        return render_template('messages/message.html', message=message, sender_nickname=sender_nickname,
                               reciver_nickname=reciver_nickname, is_a_note=message.is_a_noteOBJ, note=note)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='message message reading')
        Error_obj.save_to_mongo()

        return render_template('error_page.html', error_msgr='Crashed during reading message...')


@message_blueprint.route('/all_messages/')
@user_decorators.require_login
def all_messages():
    try:
        all_messagess = Message.find_all()

        return render_template('messages/all_messages.html', all_messagess=all_messagess)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='message reading')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during reading your messages...')


@message_blueprint.route('/delete_message/<string:message_id>')
@user_decorators.require_login
def delete_message(message_id):
    try:
        message = Message.find_by_id(message_id)

        message.delete()
        return redirect(url_for('.my_recived_messages', user_id=session['_id']))

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='delete_message message deleting')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during deleteing your message...')


@message_blueprint.route('/send_note', methods=['GET', 'POST'])
@user_decorators.require_login
def send_note():
    all_notes = Note.get_all()
    all_users = User.get_all()

    if request.method == 'POST':

        try:
            note = Note.find_by_id(request.form['note'])
        except:

            error_msg = traceback.format_exc().split('\n')

            Error_obj = Error_(error_msg=''.join(error_msg), error_location='send_note note finding/reading')
            Error_obj.save_to_mongo()

            return render_template('error_page.html', error_msgr='Crashed during preparing page...')

        message_title = request.form['title']

        if request.form.getlist("user") in [None, [], ""]:
            return render_template('messages/send_note.html',
                                   e="You hadn't selected an reciver. Please select at least ONE reciver.",
                                   all_users=all_users, title=message_title,)

        else:

            recivers = request.form.getlist("user")

        sender_id = User.find_by_email(session['email'])._id

        message = Message(title=message_title, content=note._id, reciver_id=recivers, sender_id=sender_id, is_a_noteOBJ=True)
        message.save_to_mongo()

        return redirect(url_for('.my_sended_messages', user_id=sender_id))

    return render_template('messages/send_note.html',
                           all_notes=all_notes, all_users=all_users)


@message_blueprint.route('/send_note_<string:note_id>', methods=['GET', 'POST'])
@user_decorators.require_login
def send_note_radio(note_id):
    note = Note.find_by_id(note_id)
    all_notes = Note.get_all()
    all_users = User.get_all()

    if request.method == 'POST':

        try:
            note = Note.find_by_id(request.form['note'])
        except:

            error_msg = traceback.format_exc().split('\n')

            Error_obj = Error_(error_msg=''.join(error_msg), error_location='send_note note finding/reading')
            Error_obj.save_to_mongo()

            return render_template('error_page.html', error_msgr='Crashed during preparing page...')

        message_title = request.form['title']

        if request.form.getlist("user") in [None, [], ""]:
            return render_template('messages/send_note.html',
                                   e="You hadn't selected an reciver. Please select at least ONE reciver.",
                                   all_users=all_users, title=message_title,)

        else:

            recivers = request.form.getlist("user")

        sender_id = User.find_by_email(session['email'])._id

        message = Message(title=message_title, content=note._id, reciver_id=recivers, sender_id=sender_id, is_a_noteOBJ=True)
        message.save_to_mongo()

        return redirect(url_for('.my_sended_messages', user_id=sender_id))

    return render_template('messages/send_note.html',
                           all_notes=all_notes, all_users=all_users, note_=note)

models/users/views.py
import datetime
import time
import traceback

from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect
import src.models.users.errors as UserErrors
from src.common.utils import Utils
from src.models.error_logs.error_log import Error_
from src.models.messages.message import Message
from src.models.notes.note import Note
from src.models.users.user import User
import src.models.users.decorators as user_decorators

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():

    try:
        e = ''
        if request.method == 'POST':

            email = request.form['email']
            password = request.form['password']

            try:
                if User.is_login_valid(email, password):
                    session['email'] = email
                    user = User.find_by_email(email)
                    session['_id'] = user._id
                    user.last_logined = datetime.datetime.now()
                    user.save_to_mongo()
                    return redirect(url_for("home"))

            except UserErrors.UserError as e:
                return render_template("users/login.html", message=e)

        return render_template("users/login.html", message=e)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='login_user while logining user')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during login...')


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():

    try:
        if request.method == 'POST':

            email = request.form['email']
            password = request.form['password']
            nick_name = request.form['nickname']

            try:
                if User.register_user(email, password, nick_name):
                    session['email'] = email
                    message = Message(title="Welcome to Note-it™!",
                                      content="""Welcome to Note-it! You can make a note,
                                            and share it with other users! Or you can
                                            just keep the note to your selves.
                                            You can send messages to other users too! Check out this website!!""",
                                      reciver_id=User.find_by_email(email)._id,
                                      sender_id=User.find_by_email('SE@SENOREPLAY.COM')._id)
                    message.save_to_db()
                    return redirect(url_for("home"))

            except UserErrors.UserError as e:
                return e.message

        return render_template("users/register.html")

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='register_user while registering user')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during registering you...')


#@user_blueprint.route('/alerts')
#@user_decorators.require_login
#def user_notes():
#    user = User.find_by_email(session['email'])
#    alerts = user.get_alerts()
#    user_name = user.email
#    return render_template('users/alerts.html', alerts=alerts, user_name=user_name)


@user_blueprint.route('/logout')
@user_decorators.require_login
def logout_user():
    session['email'] = None
    session['_id'] = None

    return redirect(url_for('home'))


@user_blueprint.route('/users', methods=['GET', 'POST'])
def users_page():
    try:
        users = User.get_all()
        # TODO: 일래스틱서치 배우고 완료하기
        return render_template('/users/users_page.html', users=users)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='users_page while loading users info and posting to html')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during reading information...')


@user_blueprint.route('/user/<string:user_id>')
def user_page(user_id):

    try:
        try:
            user = User.find_by_id(user_id)
        except:
            user = User.find_by_email(user_id)
        user_notes = Note.find_shared_notes_by_user(user.email)

        return render_template('/users/user.html', user=user, user_notes=user_notes, user_note_count=len(user_notes))

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg),
                           error_location='user_page while loading user{} info'.format(user_id))
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during reading information...')


@user_blueprint.route('/delete_user/<string:user_id>', methods=['GET', 'POST'])
@user_decorators.require_login
def delete_user(user_id):

    try:
        if request.method == 'POST':
            user = User.find_by_id(user_id)
            user.delete_user_notes()
            user.delete()
            session['email'] = None
            return redirect(url_for('home'))

        return render_template('/users/confrim.html')

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg), error_location='delete_user while removing user from database')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during deleting your account...')


@user_blueprint.route('/edit_user/<string:user_id>', methods=['GET', 'POST'])
@user_decorators.require_login
def edit_user(user_id):

    try:
        current_user = User.find_by_id(user_id)

        if request.method == 'POST':

            nick_name = request.form['nickname']

            current_user.nick_name = nick_name
            current_user.save_to_mongo()

            return redirect(url_for('.user_page', user_id=user_id))

        return render_template("users/edit_user.html", user=current_user)

    except:
        error_msg = traceback.format_exc().split('\n')

        Error_obj = Error_(error_msg=''.join(error_msg),
                           error_location='edit_user while finding user/saving changes to database')
        Error_obj.save_to_mongo()
        return render_template('error_page.html', error_msgr='Crashed during saving changes...')

templates/messages/all_messages.html
{% extends "base.html" %}
{% block title %}
    <title>Message Center™ | All Messages</title>
{% endblock %}
{% block content %}



{% endblock %}

templates/messages/message.html
{% extends "base2.html" %}
{% block title %}
    <title>Note-it™ | Message {{ message.title }}</title>
{% endblock %}

{% block content %}

    <div class="container card" style="background-color: #e8e8e8;">

        <div class="card-body">

            {% if is_a_note %}

                <p class="text-center font-weight-light">message</p>
                <h1 class="text-center font-weight-bold">{{ message.title }}</h1>

                <p class="font-weight-normal font-italic text-right text-center">From: {{ sender_nickname }}</p>
                {% if reciver_nickname.__class__.__name__ in ('list') %}
                    <p class="font-weight-normal font-italic text-right text-center">To: {{ ' / '.join(reciver_nickname) }}</p>

                {% else %}

                    <p class="font-weight-normal font-italic text-right text-center">To:</p>

                {% endif %}

                <p class="font-weight-normal font-italic text-right">Sended At: {{ message.sended_date.strftime("%Y-%m-%d at %H:%M") }}</p>
                {% if message.readed_by_reciver != False %}
                    <p class="font-weight-normal font-italic text-right">Readed At: {{ message.readed_date.strftime("%Y-%m-%d at %H:%M") }}</p>
                {% else %}
                    <p class="font-weight-normal font-italic text-right">Readed At:                                                        </p>
                {% endif %}

                <hr class="my-4">

                <h5>Content</h5>
                <br>

                <div class="container jumbotron" style="background-color:#fffd89; width:500px; margin:10px;">
                    <h3>{{ note.title }}</h3>
                    <hr class="my-4">
                    <p class="font-weight-light">{{ note.content }}</p>

                    <p class="text-muted text-right">Created At: {{ note.created_date.strftime("%Y-%m-%d at %H:%M") }}</p>

                    <a href="{{ url_for('notes.note', note_id=note._id) }}" class="text-muted">Go see this note</a>
                </div>

            {% else %}

                <p class="text-center font-weight-light">message</p>
                <h1 class="text-center font-weight-bold">{{ message.title }}</h1>


                <p class="font-weight-normal font-italic text-right text-center">From: {{ sender_nickname }}</p>
                {% if reciver_nickname.__class__.__name__ in ('list') %}
                    <p class="font-weight-normal font-italic text-right text-center">To: {{ ' / '.join(reciver_nickname) }}</p>

                {% else %}

                    <p class="font-weight-normal font-italic text-right text-center">To:</p>

                {% endif %}

                <p class="font-weight-normal font-italic text-right">Sended At: {{ message.sended_date.strftime("%Y-%m-%d at %H:%M") }}</p>
                {% if message.readed_by_reciver != False %}
                    <p class="font-weight-normal font-italic text-right">Readed At: {{ message.readed_date.strftime("%Y-%m-%d at %H:%M") }}</p>
                {% else %}
                    <p class="font-weight-normal font-italic text-right">Readed At:                                                        </p>
                {% endif %}

                <hr class="my-4">

                <h5>Content</h5>
                <br>
                <p class="font-italic">{{ message.content }}</p>

            {% endif %}
        </div>

    </div>

    <hr class="my-4">

    <div class="card container">

        <div class="card-body">

            <a class="btn btn-outline-primary" href="#">Re-Send</a>
            <a class="btn btn-outline-warning" href="{{ url_for('message.delete_message', message_id=message._id) }}">Delete</a>

        </div>

    </div>

{% endblock %}

templates/messages/my_recived_messages.html
{% extends "base2.html" %}
{% block title %}
    <title>Note-it™ | Received Messages</title>
{% endblock %}

{% block content %}

    <div class="container jumbotron">
        <h1><i class="fas fa-at"></i> {{ user_nickname }}'s Received Messages</h1>
        <hr class="my-4">

        <div class="list-group">

            {% if messages == [''] or messages == [] %}
                <div class="alert alert-info" role="alert">
                    <i class="far fa-frown"></i> No Received Messages...
                </div>
            {% else %}

                {% for message in messages %}

                <a href="{{ url_for('.message', message_id=message._id) }}" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">

                        <h5 class="mb-1 text-left">{{ '<i class="far fa-envelope-open"></i>'|safe if message.readed_by_reciver else '<i class="far fa-envelope"></i>'|safe }} {{ message.title }}</h5>
                        <small>Sended at: {{ message.sended_date.strftime("%Y-%m-%d at %H:%M") }}</small>
                    </div>
                </a>

                {% endfor %}

            {% endif %}

        </div>

    </div>

{% endblock %}

templates/messages/my_sended_messages.html
{% extends "base2.html" %}
{% block title %}
    <title>Note-it™ | Sended Messages</title>
{% endblock %}

{% block content %}

    <div class="container jumbotron">
        <h1><i class="fas fa-at"></i> {{ user_nickname }}'s Sended Messages</h1>
        <hr class="my-4">

        <div class="list-group">

            {% if messages == [''] or messages == [] %}
                <div class="alert alert-info" role="alert">
                    <i class="far fa-frown"></i> No Sended Messages...
                </div>
            {% else %}

                {% for message in messages %}

                <a href="{{ url_for('.message', message_id=message._id, is_sended=True) }}" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1"><i class="fas fa-envelope-square"></i> {{ message.title }}</h5>
                        <small>Sended at: {{ message.sended_date.strftime("%Y-%m-%d at %H:%M") }}</small>
                    </div>
                </a>

                {% endfor %}

            {% endif %}

        </div>

    </div>

{% endblock %}

templates/messages/send_message.html
{% extends "base2.html" %}
{% block title %}
    <title>Note-it™ | Send Message</title>
{% endblock %}

{% block content %}

    <div class="jumbotron form-sizer">

        <h1><i class="fas fa-external-link-square-alt"></i> Send a Message</h1>

        <p>Fill in the blanks, and send!</p>

    </div>

    <br>

    <div class="form-size jumbotron">

        <form method="POST">

            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" name="title" id="title" placeholder="Example title" aria-describedby="titleBlock" value="{{ title }}">

                <small id="titleBlock" class="form-text text-muted">Your message's title</small>
            </div>

            <div class="input-group">

                <div class="input-group-prepend">
                    <label for="content" class="input-group-text">Content</label>
                </div>

                <textarea class="form-control text_box_big" name="content" id="content" placeholder="Example content" aria-describedby="contentBlock">{{ content }}</textarea>

            </div>

            <div class="form-group">

                {% if e %}
                <br>

                <div class="alert alert-danger" role="alert">
                    <i class="fas fa-exclamation"></i>  {{ e }}
                </div>


                {% endif %}
                <label for="reciver_email">Reciver Email</label>
                <input type="text" class="form-control" name="reciver_email" id="reciver_email" placeholder="Example title" aria-describedby="reciver_emailBlock" value="">

                <small id="reciver_emailBlock" class="form-text text-muted"><i class="fas fa-exclamation-circle"></i>Copy the user's email EXACTALLY from the list blow. If you want to send this message to multiple users, please
separate the user's emails with a space, or ,.</small>
            </div>

            <br>
            <button type="submit" class="btn btn-primary">Send Message</button>

        </form>

        <hr class="my-4">


        {% if all_users == None %}
        <h1>No users are available. Please contact us <a>(010-2901-5627)</a></h1>
    {% else %}
    <div class="list-group">
        <h1 class="heading">Users <small class="text-muted">for copying</small></h1>
        <hr class="my-4">
        {% for user in all_users %}

            <a href="{{ url_for('users.user_page', user_id=user._id) }}" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ user.nick_name }}</h5>
                    <small class="text-muted">Last logined at {{ user.last_logined.strftime("%Y-%m-%d at %H:%M") }}</small>
                </div>
            </a>

        {% endfor %}

    </div>
    {% endif %}

    </div>


    <hr class="my-4">


    <div class="jumbotron container">

        <h3 class="font-weight-light">Click here if you want to send a note</h3>  <a href="{{ url_for('.send_note') }}" role="button" class="btn btn-outline-primary">Send Note</a>

    </div>

{% endblock %}

templates/messages/send_note.html
{% extends "base2.html" %}
{% block title %}
    <title>Note-it™ | Send Note</title>
{% endblock %}

{% block content %}

    <div class="jumbotron form-sizer">

        <h1><i class="fas fa-external-link-square-alt"></i> Send a Note</h1>

        <p>Select an note, than submit!</p>

    </div>

    <br>

    <div class="form-size jumbotron">

        <form method="POST">



            <div class="form-group">

                {% if e %}
                <br>

                <div class="alert alert-danger" role="alert">
                    <i class="fas fa-exclamation"></i>  {{ e }}
                </div>


                {% endif %}
                <label for="title"><b>Title</b></label>
                <input type="text" class="form-control" name="title" id="title" placeholder="Example title" aria-describedby="reciver_emailBlock" value="">

            </div>
                    <hr class="my-4">

            <div class="list-group">

                {% if note_ %}
                    <h1 class="heading">Notes <small class="text-muted">select a note you want to send</small></h1>
                    {% for note in all_notes %}

                        <b class="list-group-item list-group-item-action flex-column align-items-start">
                            <div class="d-flex w-100 justify-content-between">
                                {% if note_._id == note._id %}
                                    <input type="radio" value="{{ note._id }}" name="note" checked="checked" />
                                {% else %}

                                    <input type="radio" value="{{ note._id }}" name="note">

                                {% endif %}

                                <h5 class="mb-1">{{ note.title }}</h5>
                                <small class="text-muted">Made date {{ note.created_date.strftime("%Y-%m-%d at %H:%M") }}</small>
                            </div>
                        </b>
                    {% endfor %}

                {% else %}

                    <h1 class="heading">Notes <small class="text-muted">select a note you want to send</small></h1>
                    {% for note in all_notes %}

                        <b class="list-group-item list-group-item-action flex-column align-items-start">
                            <div class="d-flex w-100 justify-content-between">
                                <input type="radio" value="{{ note._id }}" name="note" />
                                <h5 class="mb-1">{{ note.title }}</h5>
                                <small class="text-muted">Made date {{ note.created_date.strftime("%Y-%m-%d at %H:%M") }}</small>
                            </div>
                        </b>

                    {% endfor %}

                {% endif %}



    </div>

                    <hr class="my-4">

             {% if all_users == None %}
        <h1>No users are available. Please contact us <a>(010-2901-5627)</a></h1>
    {% else %}
    <div class="list-group">
        <h1 class="heading">Users <small class="text-muted">for copying</small></h1>
        {% for user in all_users %}

            <b class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                    <input type="checkbox" value="{{ user._id }}" name="user" />
                    <h5 class="mb-1">{{ user.nick_name }}</h5>
                    <small class="text-muted">Last logined at {{ user.last_logined.strftime("%Y-%m-%d at %H:%M") }}</small>
                </div>
            </b>

        {% endfor %}

    </div>
    {% endif %}

    <br>
    <button type="submit" class="btn btn-primary">Send Message</button>


        </form>

    </div>

{% endblock %}